name: widget-server pipe

on:
  push:
    branches: 
        - 'main'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout run
        run: echo "Hello"